version: '3.1'
services:
  discovery-service:
    container_name: discovery-service
    image: discovery-service.jar
    build: D:\workspace\2\discovery-service\build\libs
    ports:
      - "8761:8761"
    depends_on:
      - signup-service
      - product-service
  signup-service:
    container_name: signup-service
    image: signup-service.jar
    build: ./
    ports:
    - "8081:8081"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=merchant,product
  product-service:
    container_name: product-service
    image: product-service.jar
    build: D:\workspace\2\product-service\build\libs
    ports:
    - "8082:8082"
    depends_on:
      - postgresdb
