defaultExpDate: 43200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  remember:
    me: 604800
  secret: secret
rememberMeExpDate: 604800
server:
  error:
    include-message: always
  port: 8081
  servlet:
    context-path: /bestcommerce
spring:
  application:
    name: signup-login-service
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/merchant
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
