eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  error:
    include-message: always
  port: 8082
  servlet:
    context-path: /products
spring:
  application:
    name: product-service
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
